spring:
  datasource:
    url: jdbc:h2:file:./data/mydb
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: true  # ⭐️ H2 웹 콘솔 활성화
      path: /h2-console # ⭐️ 콘솔에 접근할 URL 경로 설정

  data:
    redis:
      host: ${REDIS_HOST}  # Redis 설치한 IP (로컬이면 보통 127.0.0.1)
      port: ${REDIS_PORT}      # Redis 기본 포트
      # password: yourpassword # 비밀번호 설정했으면 추가

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        id:
          new_generator_mappings: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  refresh-expiration: 604800000

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_BUCKET_NAME}

server:
  port: 8080

frontend:
  url: ${FRONTEND_URL}


logging:
  level:
    # ⭐️ 스키마 생성 관련 로그를 반드시 확인하기 위해 INFO 레벨로 설정
    org.hibernate.tool.hbm2ddl: INFO
    # (선택) Hibernate 전체 동작을 자세히 보려면 DEBUG로 설정
    # org.hibernate: DEBUG
    # (선택) SQL 파라미터까지 확인하려면 TRACE로 설정 (이전 답변 참고)
    # org.hibernate.orm.jdbc.bind: TRACE