spring:
  # ----------------------------------------------------
  # 1. H2 데이터소스 연결 설정
  # ----------------------------------------------------
  datasource:
    # URL: 파일 기반 H2 설정
    #   - ./db/myproject.mv.db 파일로 저장되어 데이터가 유지됩니다.
    url: jdbc:h2:file:./db/myproject
    username: sa # H2 기본 사용자명
    password: # 비밀번호 없음
    driver-class-name: org.h2.Driver

  # ----------------------------------------------------
  # 2. JPA/Hibernate 설정
  # ----------------------------------------------------
  jpa:
    hibernate:
      # 개발 단계에서는 엔티티 변경 시 테이블 구조를 자동 업데이트합니다.
      ddl-auto: create-drop
    properties:
      hibernate:
        # DB 방언을 H2Dialect로 지정 (매우 중요)
        dialect: org.hibernate.dialect.H2Dialect
        # SQL 쿼리를 콘솔에 예쁘게 포맷하여 출력
        format_sql: true
        show_sql: true

  # ----------------------------------------------------
  # 3. H2 Console 설정 (브라우저에서 DB 확인용)
  # ----------------------------------------------------
  h2:
    console:
      # H2 콘솔 활성화
      enabled: true
      # 콘솔 접속 경로 (http://localhost:8080/h2-console 로 접속)
      path: /h2-console

  data:
    redis:
      host: ${REDIS_HOST}  # Redis 설치한 IP (로컬이면 보통 127.0.0.1)
      port: ${REDIS_PORT}      # Redis 기본 포트
      # password: yourpassword # 비밀번호 설정했으면 추가
